create role "admin";


create table "public"."category" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."category" enable row level security;

create table "public"."image" (
    "id" bigint generated by default as identity not null,
    "category_id" bigint not null,
    "title" text not null,
    "artist" text not null,
    "motive_height" bigint not null,
    "motive_width" bigint not null,
    "height" bigint not null,
    "width" bigint not null,
    "price" bigint not null,
    "notice" text,
    "image_path" text not null
);


alter table "public"."image" enable row level security;

create table "public"."image_to_topic_folder" (
    "image_id" bigint not null,
    "topic_folder_id" bigint not null
);


alter table "public"."image_to_topic_folder" enable row level security;

create table "public"."selection" (
    "image_id" bigint not null,
    "customer_id" uuid not null,
    "pallet" text,
    "strip" text,
    "passepartout" boolean not null,
    "is_recommendation" boolean not null,
    "id" bigint generated by default as identity not null
);


alter table "public"."selection" enable row level security;

create table "public"."topic_folder" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text
);


alter table "public"."topic_folder" enable row level security;

CREATE UNIQUE INDEX category_id_key ON public.category USING btree (id);

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX image_to_topic_folder_pkey ON public.image_to_topic_folder USING btree (image_id, topic_folder_id);

CREATE UNIQUE INDEX picture_id_key ON public.image USING btree (id);

CREATE UNIQUE INDEX picture_pkey ON public.image USING btree (id);

CREATE UNIQUE INDEX selection_id_key ON public.selection USING btree (id);

CREATE UNIQUE INDEX selection_pkey ON public.selection USING btree (id);

CREATE UNIQUE INDEX topic_folder_pkey ON public.topic_folder USING btree (id);

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."image" add constraint "picture_pkey" PRIMARY KEY using index "picture_pkey";

alter table "public"."image_to_topic_folder" add constraint "image_to_topic_folder_pkey" PRIMARY KEY using index "image_to_topic_folder_pkey";

alter table "public"."selection" add constraint "selection_pkey" PRIMARY KEY using index "selection_pkey";

alter table "public"."topic_folder" add constraint "topic_folder_pkey" PRIMARY KEY using index "topic_folder_pkey";

alter table "public"."category" add constraint "category_id_key" UNIQUE using index "category_id_key";

alter table "public"."image" add constraint "picture_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category(id) not valid;

alter table "public"."image" validate constraint "picture_category_id_fkey";

alter table "public"."image" add constraint "picture_id_key" UNIQUE using index "picture_id_key";

alter table "public"."image_to_topic_folder" add constraint "image_to_topic_folder_image_id_fkey" FOREIGN KEY (image_id) REFERENCES image(id) not valid;

alter table "public"."image_to_topic_folder" validate constraint "image_to_topic_folder_image_id_fkey";

alter table "public"."image_to_topic_folder" add constraint "picture_to_topic_folder_topic_folder_id_fkey" FOREIGN KEY (topic_folder_id) REFERENCES topic_folder(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."image_to_topic_folder" validate constraint "picture_to_topic_folder_topic_folder_id_fkey";

alter table "public"."selection" add constraint "selection_id_key" UNIQUE using index "selection_id_key";

alter table "public"."selection" add constraint "selection_image_id_fkey" FOREIGN KEY (image_id) REFERENCES image(id) ON DELETE CASCADE not valid;

alter table "public"."selection" validate constraint "selection_image_id_fkey";

grant delete on table "public"."category" to "anon";

grant insert on table "public"."category" to "anon";

grant references on table "public"."category" to "anon";

grant select on table "public"."category" to "anon";

grant trigger on table "public"."category" to "anon";

grant truncate on table "public"."category" to "anon";

grant update on table "public"."category" to "anon";

grant delete on table "public"."category" to "authenticated";

grant insert on table "public"."category" to "authenticated";

grant references on table "public"."category" to "authenticated";

grant select on table "public"."category" to "authenticated";

grant trigger on table "public"."category" to "authenticated";

grant truncate on table "public"."category" to "authenticated";

grant update on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant select on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant update on table "public"."category" to "service_role";

grant delete on table "public"."image" to "anon";

grant insert on table "public"."image" to "anon";

grant references on table "public"."image" to "anon";

grant select on table "public"."image" to "anon";

grant trigger on table "public"."image" to "anon";

grant truncate on table "public"."image" to "anon";

grant update on table "public"."image" to "anon";

grant delete on table "public"."image" to "authenticated";

grant insert on table "public"."image" to "authenticated";

grant references on table "public"."image" to "authenticated";

grant select on table "public"."image" to "authenticated";

grant trigger on table "public"."image" to "authenticated";

grant truncate on table "public"."image" to "authenticated";

grant update on table "public"."image" to "authenticated";

grant delete on table "public"."image" to "service_role";

grant insert on table "public"."image" to "service_role";

grant references on table "public"."image" to "service_role";

grant select on table "public"."image" to "service_role";

grant trigger on table "public"."image" to "service_role";

grant truncate on table "public"."image" to "service_role";

grant update on table "public"."image" to "service_role";

grant delete on table "public"."image_to_topic_folder" to "anon";

grant insert on table "public"."image_to_topic_folder" to "anon";

grant references on table "public"."image_to_topic_folder" to "anon";

grant select on table "public"."image_to_topic_folder" to "anon";

grant trigger on table "public"."image_to_topic_folder" to "anon";

grant truncate on table "public"."image_to_topic_folder" to "anon";

grant update on table "public"."image_to_topic_folder" to "anon";

grant delete on table "public"."image_to_topic_folder" to "authenticated";

grant insert on table "public"."image_to_topic_folder" to "authenticated";

grant references on table "public"."image_to_topic_folder" to "authenticated";

grant select on table "public"."image_to_topic_folder" to "authenticated";

grant trigger on table "public"."image_to_topic_folder" to "authenticated";

grant truncate on table "public"."image_to_topic_folder" to "authenticated";

grant update on table "public"."image_to_topic_folder" to "authenticated";

grant delete on table "public"."image_to_topic_folder" to "service_role";

grant insert on table "public"."image_to_topic_folder" to "service_role";

grant references on table "public"."image_to_topic_folder" to "service_role";

grant select on table "public"."image_to_topic_folder" to "service_role";

grant trigger on table "public"."image_to_topic_folder" to "service_role";

grant truncate on table "public"."image_to_topic_folder" to "service_role";

grant update on table "public"."image_to_topic_folder" to "service_role";

grant delete on table "public"."selection" to "anon";

grant insert on table "public"."selection" to "anon";

grant references on table "public"."selection" to "anon";

grant select on table "public"."selection" to "anon";

grant trigger on table "public"."selection" to "anon";

grant truncate on table "public"."selection" to "anon";

grant update on table "public"."selection" to "anon";

grant delete on table "public"."selection" to "authenticated";

grant insert on table "public"."selection" to "authenticated";

grant references on table "public"."selection" to "authenticated";

grant select on table "public"."selection" to "authenticated";

grant trigger on table "public"."selection" to "authenticated";

grant truncate on table "public"."selection" to "authenticated";

grant update on table "public"."selection" to "authenticated";

grant delete on table "public"."selection" to "service_role";

grant insert on table "public"."selection" to "service_role";

grant references on table "public"."selection" to "service_role";

grant select on table "public"."selection" to "service_role";

grant trigger on table "public"."selection" to "service_role";

grant truncate on table "public"."selection" to "service_role";

grant update on table "public"."selection" to "service_role";

grant delete on table "public"."topic_folder" to "anon";

grant insert on table "public"."topic_folder" to "anon";

grant references on table "public"."topic_folder" to "anon";

grant select on table "public"."topic_folder" to "anon";

grant trigger on table "public"."topic_folder" to "anon";

grant truncate on table "public"."topic_folder" to "anon";

grant update on table "public"."topic_folder" to "anon";

grant delete on table "public"."topic_folder" to "authenticated";

grant insert on table "public"."topic_folder" to "authenticated";

grant references on table "public"."topic_folder" to "authenticated";

grant select on table "public"."topic_folder" to "authenticated";

grant trigger on table "public"."topic_folder" to "authenticated";

grant truncate on table "public"."topic_folder" to "authenticated";

grant update on table "public"."topic_folder" to "authenticated";

grant delete on table "public"."topic_folder" to "service_role";

grant insert on table "public"."topic_folder" to "service_role";

grant references on table "public"."topic_folder" to "service_role";

grant select on table "public"."topic_folder" to "service_role";

grant trigger on table "public"."topic_folder" to "service_role";

grant truncate on table "public"."topic_folder" to "service_role";

grant update on table "public"."topic_folder" to "service_role";


