name: Build and create artifact on tag
on:
    push: 
        tags: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print working directory
        run: "echo Working directory: $(pwd)"
      - name: "Change directory to project folder"
        run: cd project_micheal_angelo
      - name: Install dependencies
        run: npm install
      - name: Build   
        run: npm run build
      - name: Create artifact
        uses: actions/upload-artifact@v3

        with:
            name: michael-angelo-${{ github.ref_name }}
            path: out