name: Release to Production

on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Get release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Sync pre-production to production
        run: |
          git checkout pre-production
          
          git checkout -b release/${{ steps.get_tag.outputs.TAG }}
          
          git push origin release/${{ steps.get_tag.outputs.TAG }}:production --force
          
          git checkout pre-production
          git branch -D release/${{ steps.get_tag.outputs.TAG }}
