name: Supabase Migrations

on:
  workflow_run:
    workflows: ["Release to Production"]
    types:
      - completed
    conclusion: success
    paths:
      - 'supabase/migrations/**'

jobs:
  deploy-migrations:
    environment: production
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1.4.0

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
